name: Run Cosmos DB Emulator

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      cosmos:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
        ports:
          - 8081:8081
          - 10250-10255:10250-10255
        options: >-
          --health-cmd "curl -f https://localhost:8081/_explorer/healthcheck"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --health-start-period 30s
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install certificate
        run: |
          sudo curl -ksf "https://localhost:8081/_explorer/emulator.pem" -o '/usr/local/share/ca-certificates/cosmos.crt'
          sudo update-ca-certificates

      - name: Run Example
        working-directory: ./src/Example
        run: dotnet run
          
